name: napoli_drivers_app
description: "Napoli Pizzeria - Drivers App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2
  
  # Navigation
  go_router: ^14.2.0
  
  # Data & Persistence
  shared_preferences: ^2.2.2
  json_annotation: ^4.9.0
  supabase_flutter: ^2.9.0
  
  # Functional Programming
  fpdart: ^1.1.0
  
  # External Integrations
  url_launcher: ^6.2.5
  image_picker: ^1.0.7
  
  # Utilities
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Testing
  mocktail: ^1.0.3
  
  # Code Generation
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1
  
  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Book.otf
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Roman.otf
          weight: 400
        - asset: assets/fonts/avenir_ff/AvenirLTStd-Black.otf
          weight: 900
